name: Kits
version: ${project.version}
main: com.nelsontron.kits.Main
depend: [ Core ]
api-version: 1.13
authors: [nelsontron]
description: A customizable kit plugin
website: nelsontron.com
commands:
  kit: