name: Warps
version: ${project.version}
main: com.nelsontron.warps.Main
softdepend: [ Core ]
api-version: 1.13
authors: [nelsontron]
description: a simplistic warp plugin
website: nelsontron.com
commands:
  warp:
    aliases:
      - w
    permission: warps.use
